### ISSUE TITLE
Change the constructors structure

### ISSUE THREAD

**Issue by RolandNaijuka** [googleinterns/step141-2020#71]
- [x] allow the constructor to take in objects in form of interfaces
- [x] add optional parameters
For instance
Battery
`constructor(x:number, y:number)` could be written as
`constructor(batteryParams)` where 
``` 
interface batteryParams {
   x: number,
   y: number,
}
```

**Comment by cwlarson-google** [comment]
Note: This is more important for constructors/methods with many params.  If there are 1-3 params, it could be considered overcomplication depending on the situation

**Comment by RolandNaijuka** [comment]
> Note: This is more important for constructors/methods with many params. If there are 1-3 params, it could be considered overcomplication depending on the situation

I will fix the methods one. I just saw your comment after putting in a PR for the ones for the constructors
